### ISSUE TITLE
1.0 roadmap

### ISSUE THREAD

**Issue by wittydeveloper** [wittydeveloper/react-apollo-form#5]
- [x] code documentation
- [x] unit tests (https://github.com/wittydeveloper/react-apollo-form/pull/6)
- [ ] fix [all bugs](https://github.com/wittydeveloper/react-apollo-form/milestone/1)
- [x] badges
- [ ] storybook hosted on `gh-pages` https://github.com/wittydeveloper/react-apollo-form/pull/2
- [ ] umd build
